### ISSUE TITLE
Pod crashes when we deploy 1.5.0

### ISSUE THREAD

**Issue by BunkerHarb** [Azure/application-gateway-kubernetes-ingress#1333]
**Describe the bug**
when we deploy 1.5.0 with ingressclass disbaled we get following error:

```
I0202 11:17:59.105168       1 utils.go:114] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14d360e]

goroutine 1 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.NewContext({_, _}, {_, _}, {_, _}, {_, _}, {0x2889330, 0x0, ...}, ...)
	/azure/pkg/k8scontext/context.go:87 +0x76e
main.main()
	/azure/cmd/appgw-ingress/main.go:103 +0x59c
```

**Ingress Controller details**
```
█~█ kubectl describe pod agic-ingress-azure-f9c8fbcb-mz57k -n agic
Name:         agic-ingress-azure-f9c8fbcb-mz57k
Namespace:    agic
Priority:     0
Node:         aks-pool01-27799878-vmss00001u/10.246.34.128
Start Time:   Wed, 02 Feb 2022 11:25:38 +0100
Labels:       aadpodidbinding=agic-ingress-azure
              app=ingress-azure
              pod-template-hash=f9c8fbcb
              release=agic
Annotations:  checksum/config: 696d950853ef2c78554cb3e2c4db9601538c3a13b93d4681a872c7ac30fe3562
              fluentbit.io/parser: weirdgo
              prometheus.io/port: 8123
              prometheus.io/scrape: true
              repo: global.kubernetes
Status:       Running
IP:           10.246.34.129
IPs:
  IP:           10.246.34.129
Controlled By:  ReplicaSet/agic-ingress-azure-f9c8fbcb
Containers:
  ingress-azure:
    Container ID:   docker://4e3540f63475c4b6705301a7e71edbe657ddabff34a0d20f27a768e70d06d7b7
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:d3f2df83ef3e93acbd127208fcca607dbf825fa90a75de7e218aa05960555c97
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 02 Feb 2022 12:17:59 +0100
      Finished:     Wed, 02 Feb 2022 12:17:59 +0100
    Ready:          False
    Restart Count:  15
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      agic-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  agic-ingress-azure-f9c8fbcb-mz57k (v1:metadata.name)
      AGIC_POD_NAMESPACE:             agic (v1:metadata.namespace)
    Mounts:
      /etc/appgw/ from azure (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from agic-sa-ingress-azure-token-n9w9n (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/
    HostPathType:  Directory
  agic-sa-ingress-azure-token-n9w9n:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  agic-sa-ingress-azure-token-n9w9n
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  56m                  default-scheduler  Successfully assigned agic/agic-ingress-azure-f9c8fbcb-mz57k to aks-pool01-27799878-vmss00001u
  Normal   Pulling    55m (x4 over 56m)    kubelet            Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.0"
  Normal   Pulled     55m (x4 over 56m)    kubelet            Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.0"
  Normal   Created    55m (x4 over 56m)    kubelet            Created container ingress-azure
  Normal   Started    55m (x4 over 56m)    kubelet            Started container ingress-azure
  Warning  BackOff    69s (x264 over 56m)  kubelet            Back-off restarting failed container
█~█

**Comment by akshaysngupta** [comment]
can you also share your k8s version ?

**Comment by BunkerHarb** [comment]
we are stuck on: 1.18.8

and yes, i did disable the ingress class
