### ISSUE TITLE
AGIC crashed at Applcation Gateway doesn't have a public IP

### ISSUE THREAD

**Issue by galiacheng** [Azure/application-gateway-kubernetes-ingress#1400]
**Describe the bug**
AGIC 1.5.1 crashed when working with internal Application Gateway, error message:
```
F0531 10:05:48.200347       1 main.go:192] Got a fatal validation error on existing Application Gateway config. Please update Application Gateway or the controller's helm config. Error:Code="ErrorNoPublicIP" Message="Applcation Gateway doesn't have a public IP"
```

**To Reproduce**

1. Create internal Application Gateway:
 Ffollow [Configure an application gateway with an internal load balancer (ILB) endpoint](https://docs.microsoft.com/en-us/azure/application-gateway/configure-application-gateway-with-private-frontend-ip) to provision **Standard** tier application gateway on subnet(10.3.0.0/28). The frontend IP is `10.3.0.6`.

2. Enable AGIC 1.5.1
See helm configuration:
```yaml
# This file contains the essential configs for the ingress controller Helm chart

# Verbosity level of the App Gateway Ingress Controller
verbosityLevel: 3

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: 260524c9-7a4d-4483-8d85-de54f9c40ae8
    resourceGroup: haiche-aks-1-gateway-1
    name: appgw1voa5jhws7maoc
    usePrivateIP: true

    # Setting appgw.shared to "true" will create an AzureIngressProhibitedTarget CRD.
    # This prohibits AGIC from applying config for any host/path.
    # Use "kubectl get AzureIngressProhibitedTargets" to view and change this.
    shared: false

################################################################################
# Specify which Kubernetes namespace the ingress controller will watch
# Default value is "default"
# Leaving this variable out or setting it to blank or empty string would
# result in ingress controller observing all acessible namespaces.
#
kubernetes:
  watchNamespace: sample-domain1-ns

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
# armAuth:
#    type: aadPodIdentity
#    identityResourceID: 
#    identityClientID: 

armAuth:
    type: servicePrincipal
    secretJSON: <secret>

################################################################################
# Specify if the cluster is RBAC enabled or not
rbac:
  # Specifies whether RBAC resources should be created
  create: true
```

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
```text
Name:         ingress-azure-7bb7749d8-q7bm7
Namespace:    default
Priority:     0
Node:         aks-agentpool-13946896-vmss000001/10.224.0.5
Start Time:   Tue, 31 May 2022 18:04:52 +0800
Labels:       app=ingress-azure
              pod-template-hash=7bb7749d8
              release=ingress-azure
Annotations:  checksum/config: 54f7501e40746d9d906a2ad5724979802a2e47f15ed8c3bad717d2c9cce9cf5c
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.244.1.12
IPs:
  IP:           10.244.1.12
Controlled By:  ReplicaSet/ingress-azure-7bb7749d8
Containers:
  ingress-azure:
    Container ID:   containerd://aaa26aa5dd34b3d4b465d99d09eee198b9df107628681f8760ee7e4865e54b74
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.1
    Image ID:       mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:cc131292df265926942e23ca5601a3de66e8feabcb81f705d8f7d84b740f81b6
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 31 May 2022 18:21:02 +0800
      Finished:     Tue, 31 May 2022 18:21:03 +0800
    Ready:          False
    Restart Count:  8
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-7bb7749d8-q7bm7 (v1:metadata.name)
      AGIC_POD_NAMESPACE:             default (v1:metadata.namespace)
      AZURE_AUTH_LOCATION:            /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /etc/appgw/ from azure (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7nb6q (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/
    HostPathType:  Directory
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  kube-api-access-7nb6q:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  19m                   default-scheduler  Successfully assigned default/ingress-azure-7bb7749d8-q7bm7 to aks-agentpool-13946896-vmss000001
  Normal   Pulled     19m                   kubelet            Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.1" in 129.696054ms
  Normal   Pulled     19m                   kubelet            Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.1" in 100.958457ms
  Normal   Pulled     19m                   kubelet            Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.1" in 75.482394ms
  Normal   Created    19m (x4 over 19m)     kubelet            Created container ingress-azure
  Normal   Started    19m (x4 over 19m)     kubelet            Started container ingress-azure
  Normal   Pulling    19m (x4 over 19m)     kubelet            Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.1"
  Normal   Pulled     19m                   kubelet            Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.1" in 98.417938ms
  Warning  BackOff    4m54s (x82 over 19m)  kubelet            Back-off restarting failed container
```
* Output of `kubectl logs <ingress controller>. 
```
I0531 10:05:47.700084       1 utils.go:114] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0531 10:05:47.743106       1 supported_apiversion.go:70] server version is: 1.21.9
I0531 10:05:47.763709       1 main.go:118] Using User Agent Suffix='ingress-azure-7bb7749d8-q7bm7' when communicating with ARM
I0531 10:05:47.763995       1 main.go:137] Application Gateway Details: Subscription="260524c9-7a4d-4483-8d85-de54f9c40ae8" Resource Group="haiche-aks-1-gateway-1" Name="appgw1voa5jhws7maoc"
I0531 10:05:47.764060       1 auth.go:38] Creating authorizer from file referenced by environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0531 10:05:47.765078       1 httpserver.go:57] Starting API Server on :8123
I0531 10:05:48.112538       1 main.go:186] Ingress Controller will observe the following namespaces:sample-domain1-ns
F0531 10:05:48.200347       1 main.go:192] Got a fatal validation error on existing Application Gateway config. Please update Application Gateway or the controller's helm config. Error:Code="ErrorNoPublicIP" Message="Applcation Gateway doesn't have a public IP"
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x2858520, 0x3, {0x0, 0x0}, 0xc00022ab60, 0x1, {0x1f73ff3, 0xc00005e800}, 0xc000468360, 0x0)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x63d
k8s.io/klog/v2.(*loggingT).printDepth(0x0, 0x46056, {0x0, 0x0}, {0x0, 0x0}, 0x13, {0xc000468360, 0x2, 0x2})
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:735 +0x1ba
k8s.io/klog/v2.(*loggingT).print(...)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:717
k8s.io/klog/v2.Fatal(...)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1494
main.main()
        /azure/cmd/appgw-ingress/main.go:192 +0x176e

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
        /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xfb

goroutine 38 [IO wait]:
internal/poll.runtime_pollWait(0x7fd2c0666208, 0x72)
        /usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000167280, 0x7fd2c0645eb8, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000167280)
        /usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc000167280)
        /usr/local/go/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc00046b410)
        /usr/local/go/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc00046b410)
        /usr/local/go/src/net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc0005441c0, {0x1b21de8, 0xc00046b410})
        /usr/local/go/src/net/http/server.go:3001 +0x394
net/http.(*Server).ListenAndServe(0xc0005441c0)
        /usr/local/go/src/net/http/server.go:2930 +0x7d
github.com/Azure/application-gateway-kubernetes-ingress/pkg/httpserver.(*httpServer).Start.func1()
        /azure/pkg/httpserver/httpserver.go:58 +0xcb
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/httpserver.(*httpServer).Start
        /azure/pkg/httpserver/httpserver.go:56 +0x5b

goroutine 57 [IO wait]:
internal/poll.runtime_pollWait(0x7fd2c0666038, 0x72)
        /usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00057a980, 0xc0006b4000, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00057a980, {0xc0006b4000, 0x1c24, 0x1c24})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00057a980, {0xc0006b4000, 0xc0006b400d, 0x8e8})
        /usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0004660e8, {0xc0006b4000, 0x1c17, 0xc00006d7f8})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00046a558, {0xc0006b4000, 0x0, 0x40b4cd})
        /usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00029ecf8, {0x1af9a20, 0xc00046a558})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00029ea80, {0x1afb880, 0xc0004660e8}, 0x1c24)
        /usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00029ea80, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00029ea80, {0xc00097e000, 0x1000, 0x0})
        /usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
net/http.(*persistConn).Read(0xc000268900, {0xc00097e000, 0xc0001e80c0, 0xc00006dd30})
        /usr/local/go/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc000398240)
        /usr/local/go/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc000398240, 0x1)
        /usr/local/go/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc000268900)
        /usr/local/go/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1747 +0x1e05

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7fd2c06663d8, 0x72)
        /usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000410480, 0xc00054c000, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000410480, {0xc00054c000, 0x2c70, 0x2c70})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000410480, {0xc00054c000, 0xc00054c062, 0x310})
        /usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000010008, {0xc00054c000, 0x418886, 0xc00053d7f0})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0002d2180, {0xc00054c000, 0x0, 0x40b4cd})
        /usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00029e278, {0x1af9a20, 0xc0002d2180})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00029e000, {0x1afb880, 0xc000010008}, 0x2c13)
        /usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00029e000, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00029e000, {0xc000175000, 0x1000, 0xc00007e480})
        /usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc0004bbb60, {0xc000544038, 0x9, 0xc0002ad940})
        /usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1af9880, 0xc0004bbb60}, {0xc000544038, 0x9, 0x9}, 0x9)
        /usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader({0xc000544038, 0x9, 0xc00005ec00}, {0x1af9880, 0xc0004bbb60})
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000544000)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/frame.go:492 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00053dfa0)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/transport.go:1819 +0x165
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000162900)
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/transport.go:1741 +0x79
created by golang.org/x/net/http2.(*Transport).newClientConn
        /go/pkg/mod/golang.org/x/net@v0.0.0-20210428140749-89ef3d95e781/http2/transport.go:705 +0xb45

goroutine 26 [chan receive]:
k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc00007cd80)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/watch/mux.go:247 +0x49
created by k8s.io/apimachinery/pkg/watch.NewLongQueueBroadcaster
        /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/watch/mux.go:89 +0x11b

goroutine 27 [chan receive]:
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
        /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/record/event.go:301 +0x98
created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
        /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/record/event.go:299 +0x91

goroutine 28 [chan receive]:
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
        /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/record/event.go:301 +0x98
created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
        /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/record/event.go:299 +0x91

goroutine 48 [IO wait]:
internal/poll.runtime_pollWait(0x7fd2c0666120, 0x72)
        /usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000575480, 0xc0000c9500, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000575480, {0xc0000c9500, 0x1483, 0x1483})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000575480, {0xc0000c9500, 0xc0000c950d, 0x8be})
        /usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0004667a0, {0xc0000c9500, 0x1476, 0xc00006f7f8})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00000e090, {0xc0000c9500, 0x0, 0x40b4cd})
        /usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc00029e5f8, {0x1af9a20, 0xc00000e090})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00029e380, {0x1afb880, 0xc0004667a0}, 0xc00006f8a0)
        /usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00029e380, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc00029e380, {0xc000158000, 0x1000, 0x1})
        /usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
net/http.(*persistConn).Read(0xc000268c60, {0xc000158000, 0xc000691b60, 0xc00006fd30})
        /usr/local/go/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc0003983c0)
        /usr/local/go/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc0003983c0, 0x1)
        /usr/local/go/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc000268c60)
        /usr/local/go/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1747 +0x1e05

goroutine 49 [select]:
net/http.(*persistConn).writeLoop(0xc000268c60)
        /usr/local/go/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1748 +0x1e65

goroutine 58 [select]:
net/http.(*persistConn).writeLoop(0xc000268900)
        /usr/local/go/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1748 +0x1e65
```
* Any Azure support tickets associated with this issue.

**Comment by kchervonets** [comment]
@galiacheng I just got the same problem, did you find any solutions?

**Comment by standaloneSA** [comment]
Same problem here. Have a Standard_v2 application gateway with the EnableApplicationGatewayNetworkIsolation preview, and the controller is throwing 

Error:Code="ErrorNoPublicIP" Message="Applcation Gateway doesn't have a public IP"

**Comment by coolhome** [comment]
I'm curious if the AGIC was never updated to handle a fully private appgw?

https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1423#issuecomment-1194455124
