### ISSUE TITLE
RoleAssignmentUpdateNotPermitted when installing the azure template

### ISSUE THREAD

**Issue by hrcerqueira** [Azure/application-gateway-kubernetes-ingress#363]
**Describe the bug**
I have been trying to create a new deployment and following the Greenfield Deployment instructions.  However I get the an error when creating the custom template deployment. It is failing in the `RoleAssignmentDeploymentForUserAssignedIdentity` step with a status of bad request and the error:

```
{
  "error": {
    "code": "RoleAssignmentUpdateNotPermitted",
    "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
  }
}
```

Then, if I continue and setup teh ingress controller, it fails with the following:

```
ERROR: logging before flag.Parse: I0708 16:01:44.698588 1 main.go:233] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL I0708 16:01:44.698680 1 main.go:168] Creating authorizer from Azure Managed Service Identity E0708 16:01:44.889994 1 main.go:179] Error getting Application Gatewayapplicationgatewayaf11network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '37e18f99-8396-4ab5-b33c-6c98963d6508' with object id '37e18f99-8396-4ab5-b33c-6c98963d6508' does not have authorization to perform action 'Microsoft.Network/applicationGateways/read' over scope '/subscriptions/528561b4-271e-45f5-8636-221dc98cdc71/resourceGroups/strike-staginng/providers/Microsoft.Network/applicationGateways/applicationgatewayaf11'." I0708 16:01:44.890045 1 main.go:180] Retrying in 10s I0708 16:01:54.891838 1 main.go:109] Ingress Controller will observe all namespaces. panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12b89ca] goroutine 1 [running]: github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.validateFrontendIPConfiguration(0x185e4e0, 0xc00054a040, 0x0, 0xc000042056, 0x24, 0xc000044045, 0xf, 0xc00004400b, 0x16, 0x0, ...) /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/validators.go:119 +0x3a github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.FatalValidateOnExistingConfig(0x185e4e0, 0xc00054a040, 0x0, 0xc000042056, 0x24, 0xc000044045, 0xf, 0xc00004400b, 0x16, 0x0, ...) /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/validators.go:153 +0xc0 main.main() /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/cmd/appgw-ingress/main.go:121 +0x83c
```

I did try several times in different resource groups, with rbac enabled and rbac disabled, etc. 

I do have another deployment created exactly the same way that is working fine. 

**To Reproduce**
I can reproduce just by trying a new greenfield deployment without any particular parameter making it fail.

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

```Name:               worn-oyster-ingress-azure-6d6b68fc47-hwj6j
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-35064155-1/90.0.0.66
Start Time:         Mon, 08 Jul 2019 16:01:28 +0000
Labels:             aadpodidbinding=worn-oyster-ingress-azure
                    app=ingress-azure
                    pod-template-hash=6d6b68fc47
                    release=worn-oyster
Annotations:        <none>
Status:             Running
IP:                 90.0.0.88
Controlled By:      ReplicaSet/worn-oyster-ingress-azure-6d6b68fc47
Containers:
  ingress-azure:
    Container ID:   docker://025e02b1ac827a102b2aaed527cd32bffae3eb5d8902331e63f9671e9795e572
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:7474a032ed48a82105b960844e32fef203067a60e9a46a5c7a298b103c38725c
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 09 Jul 2019 18:08:25 +0000
      Finished:     Tue, 09 Jul 2019 18:08:35 +0000
    Ready:          False
    Restart Count:  300
    Environment Variables from:
      worn-oyster-cm-ingress-azure  ConfigMap  Optional: false
    Environment:                    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from worn-oyster-sa-ingress-azure-token-469r6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  worn-oyster-sa-ingress-azure-token-469r6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  worn-oyster-sa-ingress-azure-token-469r6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                   From                               Message
  ----     ------   ----                  ----                               -------
  Normal   Created  36m (x295 over 26h)   kubelet, aks-agentpool-35064155-1  Created container
  Warning  BackOff  63s (x6954 over 26h)  kubelet, aks-agentpool-35064155-1  Back-off restarting failed container
```

* Output of `kubectl logs <ingress controller>. 
```
ERROR: logging before flag.Parse: I0709 18:13:46.343183       1 main.go:233] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0709 18:13:46.343272       1 main.go:168] Creating authorizer from Azure Managed Service Identity
E0709 18:13:46.516078       1 main.go:179] Error getting Application Gatewayapplicationgatewayaf11network.ApplicationGatewaysClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '37e18f99-8396-4ab5-b33c-6c98963d6508' with object id '37e18f99-8396-4ab5-b33c-6c98963d6508' does not have authorization to perform action 'Microsoft.Network/applicationGateways/read' over scope '/subscriptions/528561b4-271e-45f5-8636-221dc98cdc71/resourceGroups/strike-staginng/providers/Microsoft.Network/applicationGateways/applicationgatewayaf11'."
I0709 18:13:46.516126       1 main.go:180] Retrying in 10s
I0709 18:13:56.517416       1 main.go:109] Ingress Controller will observe all namespaces.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12b89ca]

goroutine 1 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.validateFrontendIPConfiguration(0x185e4e0, 0xc000267940, 0x0, 0xc000042056, 0x24, 0xc000044015, 0xf, 0xc00004403b, 0x16, 0x0, ...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/validators.go:119 +0x3a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.FatalValidateOnExistingConfig(0x185e4e0, 0xc000267940, 0x0, 0xc000042056, 0x24, 0xc000044015, 0xf, 0xc00004403b, 0x16, 0x0, ...)
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/validators.go:153 +0xc0
main.main()
        /gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/cmd/appgw-ingress/main.go:121 +0x83c
```

* Any Azure support tickets associated with this issue.
N/A

**Comment by akshaysngupta** [comment]
@hrcerqueira Thanks for reaching out.
There are two role assignments happening in the nested template, which one of them is failing for you?

**Comment by akshaysngupta** [comment]
@hrcerqueira Is it still happening ?

**Comment by arpitjain099** [comment]
It's still happening for me.

**Comment by snapfisher** [comment]
I am having the exact same problem.  The template installs from the CLI with no errors, but if you try to deploy it through Azure DevOps, I get this exact error.  And I have already made the Azure DevOps client and owner on the resource group. so....I'm scratching my head on this.

**Comment by DazzaDroid** [comment]
@akshaysngupta Is there a fix for this? I'm also getting the same error even when running from CLI. It worked well first time but now the greenfield deployment no longer works. Seems as though this can only be run once and the template is not idempotent with regard to the RoleAssignments. Even when all resources that were created are deleted, the deployment will fail with
{
    "error": {
        "code": "RoleAssignmentUpdateNotPermitted",
        "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
    }
}

**Comment by snapfisher** [comment]
I managed to do a non-RBAC deployment through Azure DevOps.  The arm template is brittle.  Just do not modify it.  The greenfield deployment steps do work.

**Comment by DazzaDroid** [comment]
@snapfisher have you managed to complete the steps multiple times?

**Comment by snapfisher** [comment]
Yes

On Mar 4, 2020 4:19 AM, DazzaDroid <notifications@github.com> wrote:

@snapfisher<https://github.com/snapfisher> have you managed to complete the steps multiple times?

**Comment by svishnevsky** [comment]
The same happened during creating one more cluster in the same subscription. Any ideas?

**Comment by ThomasDetemmerman** [comment]
I found the solution in [this blog post](https://jasonmasten.com/2021/04/13/tenant-id-application-id-principal-id-and-scope-are-not-allowed-to-be-updated/). 
1. Change the GUID the field "name".
2. In my case, I got a new error that the role assignment already existed. So I deleted the old one.

**Comment by johnib** [comment]
> I found the solution in [this blog post](https://jasonmasten.com/2021/04/13/tenant-id-application-id-principal-id-and-scope-are-not-allowed-to-be-updated/).
> 
> 1. Change the GUID in the field `name`.
> 2. In my case, I got a new error that the role assignment already existed. So I deleted the old one.

#1 is the issue most probably.
When you assign a role, the _assignment_ needs to have some identifier (unique).
If you happen to pick an existing identifier for a new assignment, that is the error you'll get.
