### ISSUE TITLE
DistrubutedSession error: Operation cancelled by user

### ISSUE THREAD

**Issue by knoxi** [Azure/application-gateway-kubernetes-ingress#463]
When I run my web app within an AKS with application gateway ingress controller, I'm getting an error in DistributedSession. When I run the web app within an AKS with nginx ingress controller, there is no such error in the logs.

In our service we are using Distributed SQL Server Cache and there the entry in the cache table is missing because of this exception. We use the same sql server connection string for reading data and this works fine.

Does anyone have any idea what that might be?
Because ignoring it as [mentioned here](https://github.com/aspnet/AspNetCore/issues/3479#issuecomment-508429455) is not a solution for me.

```
fail: Microsoft.AspNetCore.Session.SessionMiddleware[1]
      Error closing the session.
System.Data.SqlClient.SqlException (0x80131904): Operation cancelled by user.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.GetCacheItemAsync(String key, Boolean includeValue, CancellationToken token)
   at Microsoft.Extensions.Caching.SqlServer.DatabaseOperations.RefreshCacheItemAsync(String key, CancellationToken token)
   at Microsoft.Extensions.Caching.SqlServer.SqlServerCache.RefreshAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
ClientConnectionId:81070212-5d16-4b2d-969c-9e425aab4beb
ClientConnectionId before routing:c2bdfa1d-ad1c-4a45-bc65-c29770bc7e9b
Routing Destination:b0fa78351991.tr60.westeurope1-a.worker.database.windows.net,11048
```

**Comment by akshaysngupta** [comment]
To be sure, Are you running an SQL cache behind AppGW. This exception happens when the web frontend makes a request to the SQL cache through AppGW ?

**Comment by knoxi** [comment]
The ASP.Net Core service has enabled distributed cache service with SQL server. The distributed cache is used to store session data for multiple instances of our service. We are not using SQL cache.

**Comment by akshaysngupta** [comment]
@knoxi Can you explain what's on AKS and what traffic is flowing though Application gateway ?
Are those persistent connections, what's the life cycle of those connections ? What are the components of the system and how do they interact with each other? Also, are there any timeout restrictions ?

**Comment by knoxi** [comment]
@akshaysngupta We are running multiple instances of our ASP.Net Core service API in AKS. The SQL database is an Azure SQL DB. The whole Api requests are going though the AppGW, and I think the SQL connection as well. The service connections aren't persistent. All timeout values aren't changed from it's default values. There are no other service affected/involved except the SQL DB.

**Comment by delqn** [comment]
@knoxi It is difficult to troubleshoot this issue with limited information / logs.

My suspicion is that the SQL query executed takes longer than the default App Gateway timeout.
To test this idea - you could use [the annotation mentioned here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/9bed6a450e0bf05467aabcd0eb187b545197ec80/docs/annotations.md#request-timeout) to increase the request timeout.

Would you be so kind to set request time out to a reasonable value (in seconds) that would give you sufficient to execute the query and report how that affects the system?

**Comment by akshaysngupta** [comment]
Closing due to inactivity.
