### ISSUE TITLE
AGIC should support more than one TLS-cert for multi clusters/namespaces environments  

### ISSUE THREAD

**Issue by janhelge** [Azure/application-gateway-kubernetes-ingress#565]
We have a setup with two AKS-clusters, one supporting a domain-name (e.g *.test-domain.tld) and the other supporting a different domain-name (e.g *.prod-domain.tld). We are able to achieve correct http-routing between those AKS-clusters, but the Application Gateway is using the same TLS-certificate for both clusters (for both *.test-domain.tld and *.prod-domain.tld) As a result, only one of the AKS-clusters will have correct TLS-configuration.

The AGIC should be able to correctly support two or more domains, also regarding TLS-certificate configuration.

**Comment by draychev** [comment]
@janhelge Thanks for reporting this issue. 

Which version of AGIC are you using?

Is this a setup where 2 AGIC installations use the same App Gateway?

**Comment by janhelge** [comment]
@draychev  - Yes. We are using two separate AGIC (from two different AKS-clusters). The setup I described was using ingress-azure-0.8.0. 

On this web page ...
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/features/multiple-namespaces.md , in the paragraph "Conflicting Configurations" It says ...

> At the top of the hierarchy - listeners (IP address, port, and host) and routing rules (binding listener, backend pool and HTTP settings) could be created and shared by multiple namespaces/ingresses.
> 
> On the other hand - paths, backend pools, HTTP settings, and TLS certificates could be created by one namespace only and duplicates will removed..

Our experience was that the first AGIC instance was able to install the correct http-routing and the relevant TLS-certificate. The second AGIC instance (on the second AKS-cluster) was able to install the correct http-routing, but not the correct TLS-certificate. As a result, the ingress for the first AKS cluster was working correctly. But the ingress for the second AKS cluster was useing the wrong TLS-certificate.

One detail I should mention (I don't know if it is relevant). The AGIC was installed in same namespace-name on each AKS cluster, but the TLS-secret was named differently in the two AKS clusters

**Comment by janhelge** [comment]
In order to try to reproduce on latest release (e.g. ingress-azure-0.9.0) I have reinstalled AGIC on the "prod-AKS-cluster".  But it seems that the 0.9.0-version is having an additional issue... 
The AGIG-pod is getting errors, core-dumps. The AGIC pod is stable as long thereis no ingress, but starts to core-dump when I apply the ingress-yaml.

Here is the failing log from the AGIC-pod...
```
ERROR: logging before flag.Parse: I0928 10:28:37.248183       1 main.go:294] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0928 10:28:37.248428       1 main.go:192] Creating authorizer from Azure Managed Service Identity
I0928 10:28:37.505300       1 main.go:119] Ingress Controller will observe the following namespaces:skjemamotor
I0928 10:28:37.550974       1 context.go:122] k8s context run started
I0928 10:28:37.551165       1 context.go:161] Waiting for initial cache sync
I0928 10:28:37.652458       1 context.go:169] Initial cache sync done
I0928 10:28:37.652482       1 context.go:170] k8s context run finished
I0928 10:28:37.652610       1 worker.go:33] Worker started
I0928 10:28:37.652937       1 main.go:140] Starting Health Probe Server on :8123
I0928 10:28:37.787559       1 process.go:65] [brownfield] Prohibited targets: {"Hostname":"web.az.pit-test.no"}, {"Hostname":"dev.az.pit-test.no"}
I0928 10:28:37.787889       1 health_probes.go:67] [brownfield] Probes AGIC created: defaultprobe-Http, defaultprobe-Https, pb-skjemamotor-nginx-80-nginx
I0928 10:28:37.787908       1 health_probes.go:68] [brownfield] Existing Blacklisted Probes AGIC will retain: pb-skjemamotor-dev-motor-80-dev-motor, pb-skjemamotor-skjemamotor-80-web
I0928 10:28:37.787931       1 health_probes.go:69] [brownfield] Existing Probes AGIC will remove: 
I0928 10:28:37.788006       1 http_settings.go:68] [brownfield] HTTP Settings AGIC created: defaulthttpsetting, bp-skjemamotor-nginx-80-80-nginx
I0928 10:28:37.788038       1 http_settings.go:69] [brownfield] Existing Blacklisted HTTP Settings AGIC will retain: bp-skjemamotor-dev-motor-80-8080-dev-motor, bp-skjemamotor-skjemamotor-80-8080-web
I0928 10:28:37.788044       1 http_settings.go:70] [brownfield] Existing HTTP Settings AGIC will remove: 
I0928 10:28:37.788096       1 pools.go:67] [brownfield] Pools AGIC created: defaultaddresspool, pool-skjemamotor-nginx-80-bp-80
I0928 10:28:37.788109       1 pools.go:68] [brownfield] Existing Blacklisted Pools AGIC will retain: pool-skjemamotor-dev-motor-80-bp-8080, pool-skjemamotor-skjemamotor-80-bp-8080
I0928 10:28:37.788114       1 pools.go:69] [brownfield] Existing Pools AGIC will remove: n/a
I0928 10:28:37.788221       1 listeners.go:82] [brownfield] Listeners AGIC created: fl-anmeldelse.pub.politiet.no-443
I0928 10:28:37.788246       1 listeners.go:83] [brownfield] Existing Blacklisted Listeners AGIC will retain: fl-dev.az.pit-test.no-443, fl-dev.az.pit-test.no-80, fl-web.az.pit-test.no-443, fl-web.az.pit-test.no-80
I0928 10:28:37.788250       1 listeners.go:84] [brownfield] Existing Listeners AGIC will remove: n/a
I0928 10:28:37.788357       1 redirects.go:52] [brownfield] Redirects AGIC created: n/a
I0928 10:28:37.788362       1 redirects.go:53] [brownfield] Existing Blacklisted Redirects AGIC will retain: sslr-fl-dev.az.pit-test.no-443, sslr-fl-web.az.pit-test.no-443
I0928 10:28:37.788366       1 redirects.go:54] [brownfield] Existing Redirects AGIC will remove: n/a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11f386d]

goroutine 120 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).groupListenersByListenerIdentifier(0xc0007ba360, 0xc0007ba000, 0xc000724b48)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/frontend_listeners.go:183 +0x32d
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).getRules(0xc0007ba360, 0xc0007ba000, 0x0, 0x0, 0xc000517a40, 0x5, 0x8, 0x22ccc70)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:67 +0x6c
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).RequestRoutingRules(0xc0007ba360, 0xc0007ba000, 0x0, 0x0)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:24 +0x8a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).Build(0xc0007ba360, 0xc0007ba000, 0x0, 0x0, 0x24)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/configbuilder.go:99 +0x111
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.Process(0x16f5ac0, 0xc000267e70, 0x16f7240, 0xc00029e4e0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/process.go:115 +0xd44
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc00045a0c0, 0xc0000b97a0, 0xc0004de840)
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:48 +0x2b7
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
	/home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:65 +0x1bb
```

Here is the AzureIngressProhibitedTarget.yamls that is installed in the cluster with the failing AGIC...
```yaml
apiVersion: "appgw.ingress.k8s.io/v1"
kind: AzureIngressProhibitedTarget
metadata:
  name: web-az-pit-test-no
spec:
  hostname: web.az.pit-test.no
```

and ...
```yaml
apiVersion: "appgw.ingress.k8s.io/v1"
kind: AzureIngressProhibitedTarget
metadata:
  name: dev-az-pit-test-no
spec:
  hostname: dev.az.pit-test.no
```

Here is the ingress.yaml ...
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  tls:
  - hosts:
    - anmeldelse.pub.politiet.no
    secretName: anmeldelse-pub-politiet-no-secret-name
  rules:
    - host: anmeldelse.pub.politiet.no
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx
            servicePort: 80
```
