### ISSUE TITLE
External-DNS Causes Ingress Controller to Crash (GovCloud AKS)

### ISSUE THREAD

**Issue by flyer299** [Azure/application-gateway-kubernetes-ingress#752]
**Describe the bug**
Note, we are hosted in the VA Gov Cloud.  Not sure if this issue is related or not, just wanted to make sure those who can help are aware.

We have installed the AKS Cluster using the Greenfield Deploy and successfully setup the AGIC using help from GitHub Issues to get a version that can support the Gov Cloud. 

Then we moved on to follow this: https://github.com/kubernetes-sigs/external-dns and more specifically: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md

The ingress-azure pod continues to crash and no DNS entries are updated. 

**To Reproduce**
In the VA Gov Cloud:
1) Green Field Deploy
2)  https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

```
Name:           ingress-azure-1582659882-84b884bb97-6zfd4
Namespace:      default
Priority:       0
Node:           aks-agentpool-35064155-0/10.0.0.4
Start Time:     Mon, 02 Mar 2020 10:30:52 -0600
Labels:         aadpodidbinding=ingress-azure-1582659882
                app=ingress-azure
                pod-template-hash=84b884bb97
                release=ingress-azure-1582659882
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Running
IP:             10.0.0.11
IPs:            <none>
Controlled By:  ReplicaSet/ingress-azure-1582659882-84b884bb97
Containers:
  ingress-azure:
    Container ID:   docker://7be7ebe06c48beb1b2db480f6a90dc9e5a339b859b75e308020bd817fb910b5a
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.1-rc2
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:1543bf5f9b60534d7702ef199dd573ff2d301f3f3f8df96d99da9db7f2f7965a
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 04 Mar 2020 10:19:14 -0600
      Finished:     Wed, 04 Mar 2020 10:19:14 -0600
    Ready:          False
    Restart Count:  539
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure-1582659882  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           ingress-azure-1582659882-84b884bb97-6zfd4 (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-1582659882-token-dltfz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-1582659882-token-dltfz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-1582659882-token-dltfz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                    From                               Message
  ----     ------   ----                   ----                               -------
  Warning  BackOff  56s (x12809 over 47h)  kubelet, aks-agentpool-35064155-0  Back-off restarting failed container
```

* Output of `kubectl logs <ingress controller>. 
```
ERROR: logging before flag.Parse: I0304 16:19:14.190714       1 main.go:306] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0304 16:19:14.327509       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0304 16:19:14.327658       1 main.go:149] App Gateway Details: Subscription: fad8470a-e1a9-4209-b526-011761c080a0, Resource Group: NXT-DEV-VA, Name: SW-AG01-DEV
I0304 16:19:14.327671       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
I0304 16:19:14.327786       1 httpserver.go:57] Starting API Server on :8123
I0304 16:19:14.557851       1 main.go:191] Ingress Controller will observe all namespaces.
I0304 16:19:14.603968       1 context.go:129] k8s context run started
I0304 16:19:14.604018       1 context.go:168] Waiting for initial cache sync
I0304 16:19:14.704492       1 context.go:176] Initial cache sync done
I0304 16:19:14.704537       1 context.go:177] k8s context run finished
I0304 16:19:14.704665       1 worker.go:35] Worker started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12b6ed7]

goroutine 138 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).isServiceReferencedByAnyIngress(0xc0003cc090, 0xc0008627e0, 0x14)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:508 +0x107
github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext.(*Context).IsEndpointReferencedByAnyIngress(0xc0003cc090, 0xc0003498a8, 0xc000547c98)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/k8scontext/context.go:266 +0x11a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.ShouldProcess(0x1860000, 0xc00020a000, 0xc000042056, 0x24, 0xc000046075, 0xa, 0xc00004604b, 0xb, 0xc0004a9fb0, 0xc0003cc090, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/should_process.go:33 +0x1a2
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc000413f70, 0xc00038be00, 0xc00009f980)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:39 +0x1fd
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:72 +0x1a8
```

Also of Note:   in the Logs for External-DNS pod, I get this:
```ptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:08:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:09:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:10:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:11:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:12:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:13:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:14:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:15:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:16:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:17:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:18:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:19:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:20:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:21:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:22:12Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
time="2020-03-04T16:23:13Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
```

So I am thinking there is some sort of config or other error trying to access our subscription in Azure Gov Cloud.

* Any Azure support tickets associated with this issue.
None at this time.

**Comment by flyer299** [comment]
Additional log from the External-DNS pod right after start with the error message.  Just in case there is something useful in the start of the log:
```
time="2020-03-04T16:54:33Z" level=info msg="config: {Master: KubeConfig: RequestTimeout:30s IstioIngressGatewayServices:[] ContourLoadBalancerService:heptio-contour/contour Sources:[ingress] Namespace: AnnotationFilter: FQDNTemplate: CombineFQDNAndAnnotation:false IgnoreHostnameAnnotation:false Compatibility: PublishInternal:false PublishHostIP:false ConnectorSourceServer:localhost:8080 Provider:azure GoogleProject: GoogleBatchChangeSize:1000 GoogleBatchChangeInterval:1s DomainFilter:[] ExcludeDomains:[] ZoneIDFilter:[] AlibabaCloudConfigFile:/etc/kubernetes/alibaba-cloud.json AlibabaCloudZoneType: AWSZoneType: AWSZoneTagFilter:[] AWSAssumeRole: AWSBatchChangeSize:1000 AWSBatchChangeInterval:1s AWSEvaluateTargetHealth:true AWSAPIRetries:3 AWSPreferCNAME:false AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup:NXT-SW AzureSubscriptionID: 
AzureUserAssignedIdentityClientID: CloudflareProxied:false CloudflareZonesPerPage:50 CoreDNSPrefix:/skydns/ RcodezeroTXTEncrypt:false InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true InfobloxView: InfobloxMaxResults:0 DynCustomerName: DynUsername: DynPassword: DynMinTTLSeconds:0 OCIConfigFile:/etc/kubernetes/oci.yaml InMemoryZones:[] PDNSServer:http://localhost:8081 PDNSAPIKey: PDNSTLSEnabled:false TLSCA: TLSClientCert: TLSClientCertKey: Policy:sync Registry:txt TXTOwnerID:default TXTPrefix: Interval:1m0s Once:false DryRun:false LogFormat:text MetricsAddress::7979 LogLevel:info TXTCacheInterval:0s ExoscaleEndpoint:https://api.exoscale.ch/dns ExoscaleAPIKey: ExoscaleAPISecret: CRDSourceAPIVersion:externaldns.k8s.io/v1alpha1 CRDSourceKind:DNSEndpoint ServiceTypeFilter:[] CFAPIEndpoint: CFUsername: CFPassword: RFC2136Host: RFC2136Port:0 RFC2136Zone: RFC2136Insecure:false RFC2136TSIGKeyName: RFC2136TSIGSecret: RFC2136TSIGSecretAlg: RFC2136TAXFR:false NS1Endpoint: NS1IgnoreSSL:false TransIPAccountName: TransIPPrivateKeyFile:}"
time="2020-03-04T16:54:33Z" level=info msg="Instantiating new Kubernetes client"
time="2020-03-04T16:54:33Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2020-03-04T16:54:33Z" level=info msg="Created Kubernetes client https://10.2.0.1:443"
time="2020-03-04T16:54:34Z" level=info msg="Using client_id+client_secret to retrieve access token for Azure API."
time="2020-03-04T16:57:01Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/fad8470a-e1a9-4209-b526-011761c080a0/resourceGroups/NXT-SW/providers/Microsoft.Network/dnsZones?api-version=2018-05-01: read tcp 10.0.0.32:37126->20.44.16.113:443: read: connection reset by peer"
time="2020-03-04T16:57:01Z" level=error msg="dns.ZonesClient#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"SubscriptionNotFound\" Message=\"The subscription 'fad8470a-e1a9-4209-b526-011761c080a0' could not be found.\""
```

**Comment by flyer299** [comment]
Also note:  I opened an issue with the External-DNS Team:  https://github.com/kubernetes-sigs/external-dns/issues/1457

My leading thought is that the external-dns project needs to have a config option to enable using the Gov Cloud URL Scheme.

**Comment by akshaysngupta** [comment]
To configure AGIC correctly in US Gov cloud,  please add following to your AGIC helm config:
```yaml
appgw:
  environment: AZUREUSGOVERNMENTCLOUD
```

Regarding External DNS issue with ingress class, here is a proposal https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/proposals/multiple-gateways-single-cluster.md

cc: @garvinmsft
