### ISSUE TITLE
AGIC 1.2.0 or 1.2.0-rc3 not working with Kubernetes 1.17.7 or 1.16.9

### ISSUE THREAD

**Issue by AndresPineros** [Azure/application-gateway-kubernetes-ingress#946]
**Describe the bug**
I'm currently getting this error in the logs. It is a little frustrating because it doesn't actually let me know what is going on.
```
ERROR: logging before flag.Parse: I0710 22:52:00.078529       1 utils.go:115] Using verbosity level 5 from environment variable APPGW_VERBOSITY_LEVEL
I0710 22:52:00.110070       1 environment.go:240] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0710 22:52:00.110145       1 main.go:128] Appication Gateway Details: Subscription="<redacted>" Resource Group="p<redacted>" Name="<redacted>"
I0710 22:52:00.110152       1 auth.go:37] Creating authorizer from file referenced by environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0710 22:52:00.110177       1 httpserver.go:57] Starting API Server on :8123
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13e7d73]

goroutine 1 [running]:
main.main()
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/cmd/appgw-ingress/main.go:138 +0x1f93
```
**To Reproduce**
```
USER-SUPPLIED VALUES:
appgw:
  environment: AzureCloud
  name: <redacted>
  resourceGroup: <redacted>
  shared: false
  subscriptionId: <redacted>
  usePrivateIP: false
armAuth:
  secretJSON: <redacted>
  type: servicePrincipal
rbac:
  enabled: true
verbosityLevel: 5
```

**Ingress Controller details**
```
Name:         agic-external-ingress-ingress-azure-5b5b6bcb4d-c8db6
Namespace:    operations
Priority:     0
Node:         aks-standardd2v2-91090874-vmss000001/172.16.32.66
Start Time:   Fri, 10 Jul 2020 17:40:40 -0500
Labels:       app=ingress-azure
              pod-template-hash=5b5b6bcb4d
              release=agic-external-ingress
Annotations:  checksum/config: 542a6e79079074dfa88caee3d93c0194ba8076666402cc45cf4f78eef1c49bfe
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           172.16.32.94
IPs:
  IP:           172.16.32.94
Controlled By:  ReplicaSet/agic-external-ingress-ingress-azure-5b5b6bcb4d
Containers:
  ingress-azure:
    Container ID:   docker://ab5889530f7566580bc7fcdf7ee9a6da5281eba65a2a3eeee83a4032888f4597
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0-rc3
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:9331411a7f29cfd49b6d93e045ea6dea44cab07a2b4ce7d6a6448b3eb23d5200
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 10 Jul 2020 17:57:04 -0500
      Finished:     Fri, 10 Jul 2020 17:57:04 -0500
    Ready:          False
    Restart Count:  8
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      agic-external-ingress-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:                       /etc/appgw/azure.json
      AGIC_POD_NAME:                                       agic-external-ingress-ingress-azure-5b5b6bcb4d-c8db6 (v1:metadata.name)
      AGIC_POD_NAMESPACE:                                  operations (v1:metadata.namespace)
      AZURE_AUTH_LOCATION:                                 /etc/Azure/Networking-AppGW/auth/armAuth.json
      NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME:          prod-ca-aks
      NEW_RELIC_METADATA_KUBERNETES_NODE_NAME:              (v1:spec.nodeName)
      NEW_RELIC_METADATA_KUBERNETES_NAMESPACE_NAME:        operations (v1:metadata.namespace)
      NEW_RELIC_METADATA_KUBERNETES_POD_NAME:              agic-external-ingress-ingress-azure-5b5b6bcb4d-c8db6 (v1:metadata.name)
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_NAME:        ingress-azure
      NEW_RELIC_METADATA_KUBERNETES_CONTAINER_IMAGE_NAME:  mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0-rc3
      NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME:       agic-external-ingress-ingress-azure
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from agic-external-ingress-sa-ingress-azure-token-pgd9c (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  agic-external-ingress-sa-ingress-azure-token-pgd9c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  agic-external-ingress-sa-ingress-azure-token-pgd9c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                                           Message
  ----     ------     ----                  ----                                           -------
  Normal   Scheduled  17m                   default-scheduler                              Successfully assigned operations/agic-external-ingress-ingress-azure-5b5b6bcb4d-c8db6 to aks-standardd2v2-91090874-vmss000001
  Normal   Pulling    16m (x4 over 17m)     kubelet, aks-standardd2v2-91090874-vmss000001  Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0-rc3"
  Normal   Pulled     16m (x4 over 17m)     kubelet, aks-standardd2v2-91090874-vmss000001  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0-rc3"
  Normal   Created    16m (x4 over 17m)     kubelet, aks-standardd2v2-91090874-vmss000001  Created container ingress-azure
  Normal   Started    16m (x4 over 17m)     kubelet, aks-standardd2v2-91090874-vmss000001  Started container ingress-azure
  Warning  BackOff    2m24s (x78 over 17m)  kubelet, aks-standardd2v2-91090874-vmss000001  Back-off restarting failed container
```

Kubernetes version: tried on v1.17.7 and v1.16.9
Azure Location: canadacentral
Chart version: 1.2.0-rc3, also tried 1.2.0 with same result.

**Comment by AndresPineros** [comment]
Just found the issue. The environment is wrong, it should be AZUREPUBLICCLOUD instead of AzureCloud. I know this is on me for making a configuration mistake, but it would be nice if the application failed with a better message. I lost hours thinking it was an obscure and strange issue and didn't even double check the basic configuration because the error message was so cryptic.
